import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/header'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='max-w-[1200px] mx-auto'>
					<Header />
					{children}
				</div>
			</body>
		</html>
	)
}
